################################################################################
# This script saves the ouput from wildfire modeling. This is part of the CA 
# Biopower Impact Project.
#
# tile_number: numeric tile number.
#
# Author: Micah Wright, Humboldt State University
################################################################################

save_output <- function(dt,
                        Silvicultural_Treatment,
                        Harvest_System,
                        Harvest_Type,
                        Burn_Type,
                        tile_number,
                        year) {
        
        emissions_df <- dt[, list(x, 
                                  y,
                                  fuelbed_number,
                                  FCID2018,
                                  ID, 
                                  Silvicultural_Treatment,
                                  Harvest_Type,
                                  Harvest_System,
                                  Burn_Type,
                                  Biomass_Collection, 
                                  Year,
                                  total_char, 
                                  flaming_CH4,
                                  flaming_CH4_piled,
                                  flaming_CO,
                                  flaming_CO_piled,
                                  flaming_CO2,
                                  flaming_CO2_piled, 
                                  flaming_NH3,
                                  flaming_NH3_piled,
                                  flaming_NOx,
                                  flaming_NOx_piled,
                                  flaming_PM10,
                                  flaming_PM10_piled_clean,
                                  flaming_PM10_piled_vdirty,
                                  flaming_PM2.5,
                                  flaming_PM2.5_piled_clean,
                                  flaming_PM2.5_piled_vdirty,
                                  flaming_SO2,
                                  flaming_SO2_piled,
                                  flaming_VOC,
                                  flaming_VOC_piled,
                                  smoldering_CH4,
                                  smoldering_CH4_piled,
                                  smoldering_CO,
                                  smoldering_CO_piled,
                                  smoldering_CO2,
                                  smoldering_CO2_piled, 
                                  smoldering_NH3,
                                  smoldering_NH3_piled,
                                  smoldering_NOx,
                                  smoldering_NOx_piled,
                                  smoldering_PM10,
                                  smoldering_PM10_piled_clean,
                                  smoldering_PM10_piled_vdirty,
                                  smoldering_PM2.5,
                                  smoldering_PM2.5_piled_clean,
                                  smoldering_PM2.5_piled_vdirty,
                                  smoldering_SO2,
                                  smoldering_SO2_piled,
                                  smoldering_VOC,
                                  smoldering_VOC_piled,
                                  residual_CH4,
                                  residual_CH4_piled,
                                  residual_CO,
                                  residual_CO_piled,
                                  residual_CO2,
                                  residual_CO2_piled, 
                                  residual_NH3,
                                  residual_NH3_piled,
                                  residual_NOx,
                                  residual_NOx_piled,
                                  residual_PM10,
                                  residual_PM10_piled_clean,
                                  residual_PM10_piled_vdirty,
                                  residual_PM2.5,
                                  residual_PM2.5_piled_clean,
                                  residual_PM2.5_piled_vdirty,
                                  residual_SO2,
                                  residual_SO2_piled,
                                  residual_VOC,
                                  residual_VOC_piled,
                                  total_CH4, 
                                  total_CO, 
                                  total_CO2,
                                  total_NH3,
                                  total_NOx, 
                                  total_PM10, 
                                  total_PM2.5,
                                  total_SO2, 
                                  total_VOC)]
        
        residual_df <- dt[, list(x, 
                                 y,
                                 fuelbed_number,
                                 FCID2018, 
                                 ID, 
                                 Silvicultural_Treatment,
                                 Harvest_Type,
                                 Harvest_System,
                                 Burn_Type,
                                 Biomass_Collection, 
                                 Year,
                                 Slope,
                                 Fm10,
                                 Fm1000,
                                 Wind_corrected,
                                 duff_upper_loading,
                                 litter_loading, 
                                 one_hr_sound, 
                                 ten_hr_sound,
                                 hun_hr_sound,
                                 oneK_hr_sound,
                                 oneK_hr_rotten,
                                 tenK_hr_sound, 
                                 tenK_hr_rotten,
                                 tnkp_hr_sound,
                                 tnkp_hr_rotten,
                                 pile_field,
                                 pile_landing)]
        
        # save output
        saveRDS(emissions_df,
                file = paste0("data/Tiles/output/emissions/",
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Harvest_System,
                                    Harvest_Type,
                                    Burn_Type,
                                    tile_number,
                                    year, 
                                    sep = "-"),
                              ".rds"))
        
        saveRDS(residual_df,
                file = paste0("data/Tiles/output/residual_fuels/",
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Harvest_System,
                                    Harvest_Type,
                                    Burn_Type,
                                    tile_number,
                                    year, 
                                    sep = "-"),
                              ".rds"))
}