################################################################################
# This script saves the ouput from wildfire/RX modeling. This is part of the CA 
# Biopower Impact Project.
#
# tile_number: numeric tile number.
#
# Author: Micah Wright, Humboldt State University
################################################################################

save_output <- function(dt,
                        Silvicultural_Treatment,
                        ID,
                        Burn_Type,
                        tile_number,
                        Fraction_Piled,
                        Fraction_Scattered,
                        Biomass_Collection,
                        Pulp_Market,
                        secondary_burn,
                        year) {
        
        emissions_df <- dt[, list(x, 
                                  y,
                                  fuelbed_number,
                                  FCID2018,
                                  ID, 
                                  Silvicultural_Treatment,
                                  Burn_Type,
                                  Fraction_Piled,
                                  Fraction_Scattered,
                                  Biomass_Collection, 
                                  Pulp_Market = Pulp_Market,
                                  secondary_burn = secondary_burn,
                                  Year,
                                  total_except_pile_char,
                                  total_except_pile_CH4, 
                                  total_except_pile_CO, 
                                  total_except_pile_CO2,
                                  total_except_pile_NOx, 
                                  total_except_pile_PM10, 
                                  total_except_pile_PM2.5,
                                  total_except_pile_SO2, 
                                  total_except_pile_VOC,
                                  total_pile_clean_PM10, 
                                  total_pile_vdirty_PM10,
                                  total_pile_clean_PM2.5,
                                  total_pile_vdirty_PM2.5, 
                                  total_pile_CH4,
                                  total_pile_CO,
                                  total_pile_CO2,              
                                  total_pile_NOx,
                                  total_pile_SO2,
                                  total_pile_VOC,
                                  pile_char,
                                  char_fwd_residue,
                                  char_cwd_residue,
                                  total_duff_exposed,
                                  total_foliage_exposed,
                                  total_fwd_exposed,
                                  total_cwd_exposed,
                                  total_fuel_consumed, 
                                  total_pile_consumed,
                                  total_duff_consumed,
                                  total_foliage_consumed,
                                  total_fwd_consumed,
                                  total_cwd_consumed,
                                  total_duff_residue_CH4,      
                                  total_foliage_residue_CH4,
                                  total_fwd_residue_CH4,
                                  total_cwd_residue_CH4,    
                                  total_duff_residue_CO,
                                  total_foliage_residue_CO,
                                  total_fwd_residue_CO,
                                  total_cwd_residue_CO,
                                  total_duff_residue_CO2,
                                  total_foliage_residue_CO2,
                                  total_fwd_residue_CO2,
                                  total_cwd_residue_CO2,
                                  total_duff_residue_NOx,
                                  total_foliage_residue_NOx,
                                  total_fwd_residue_NOx,
                                  total_cwd_residue_NOx,
                                  total_duff_residue_PM10,
                                  total_foliage_residue_PM10,
                                  total_fwd_residue_PM10,
                                  total_cwd_residue_PM10,
                                  total_duff_residue_PM2.5,
                                  total_foliage_residue_PM2.5,
                                  total_fwd_residue_PM2.5,
                                  total_cwd_residue_PM2.5,
                                  total_duff_residue_SO2,
                                  total_foliage_residue_SO2,
                                  total_fwd_residue_SO2,
                                  total_cwd_residue_SO2,
                                  total_duff_residue_VOC,
                                  total_foliage_residue_VOC,
                                  total_fwd_residue_VOC,
                                  total_cwd_residue_VOC)]
        
        residual_df <- dt[, list(x, 
                                 y,
                                 fuelbed_number,
                                 FCID2018, 
                                 ID, 
                                 Silvicultural_Treatment,
                                 Burn_Type,
                                 Fraction_Piled,
                                 Fraction_Scattered,
                                 Biomass_Collection, 
                                 Pulp_Market = Pulp_Market,
                                 secondary_burn = secondary_burn,
                                 Year,
                                 Slope,
                                 Fm10,
                                 Fm1000,
                                 Wind_corrected,
                                 duff_upper_loading,
                                 litter_loading, 
                                 one_hr_sound, 
                                 ten_hr_sound,
                                 hun_hr_sound,
                                 oneK_hr_sound,
                                 oneK_hr_rotten,
                                 tenK_hr_sound, 
                                 tenK_hr_rotten,
                                 tnkp_hr_sound,
                                 tnkp_hr_rotten,
                                 pile_load)]
        
        # save output
        saveRDS(emissions_df,
                file = paste0("data/Tiles/output/emissions/",
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Burn_Type,
                                    Fraction_Piled,
                                    Fraction_Scattered,
                                    secondary_burn,
                                    Biomass_Collection,
                                    Pulp_Market,
                                    ID,
                                    tile_number,
                                    year, 
                                    sep = "-"),
                              ".rds"))
        
        saveRDS(residual_df,
                file = paste0("data/Tiles/output/residual_fuels/",
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Burn_Type,
                                    Fraction_Piled,
                                    Fraction_Scattered,
                                    secondary_burn,
                                    Biomass_Collection,
                                    Pulp_Market,
                                    ID,
                                    tile_number,
                                    year, 
                                    sep = "-"),
                              ".rds"))
}